spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri:
        -http://localhost:9000

zuul:
  routes:
    user-service:
      path: /user-service/**
      service-id: user-service
    task-service:
      path: /task-service/**
      service-id: task-service
  prefix: /api

#Eureka
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
